name: Update Readme.md

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  schedule:
    - cron: "12 12 1 * *"  # Runs at 12:12, on day 1 of the month.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: npm install
    - run: npm run start
    - run: |
        git config --global user.email "abraham.serena@hotmail.com"
        git config --global user.name "Abraham Serena"
        git add README.md
        git commit -m "[bot] Update Readme" || exit 0  # This will exit gracefully if there's nothing to commit
        git push
